id: https://w3id.org/edo/pigeon-schema
name: pigeon-schema
imports:
  - linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  pigeon: https://w3id.org/edo/pigeon/
default_range: string

classes:
  Coordination:
    slots:
      - name
  ResearchField:
    slots:
      - title
  ResearchQuestion:
    slots:
      - title
      - keywords

  Project:
    tree_root: true
    slots:
      - additional_rdm_policy
      - coordination
      - dataset
      - legal_aspects
      - partner
      - research_field
      - research_question
      - schedule
    slot_usage:
      coordination: {range: Coordination}
      research_field: {range: ResearchField}
      research_question: {range: ResearchQuestion}
  Dataset:
    slots:
      - id
      - description
      - metadata
      - preservation
      - sensitive_data
      - collaboration_organisation
  Preservation:
    slots:
      - repository
      - duration
      - responsible_person
  Person:
    slots:
      - name
      - email
  RDMPolicy:
    slots:
      - yesno
  LegalAspects:
    slots:
      - international_yesno

  Partner:
    slots:
      - name
      - contact_person
    slot_usage:
      contact_person: {range: Person}

  DatasetMetadata:
    slots:
      - title
      - description

  Schedule:
    slots:
      - project_start
      - project_end

  SensitiveData:
    slots:
      - personal_data_yesno

slots:
  # Base slots
  id: {identifier: true, range: string}
  name: {range: string}
  email: {range: string}
  description: {range: string}
  duration: {range: string}
  repository: {range: string}
  responsible_person: {range: Person}
  coordination: { range: Coordination }
  research_field: { range: ResearchField }
  research_question: { range: ResearchQuestion }
  title: {range: string}
  keywords: {range: string}

  # Structural slots (defining the links between classes)
  additional_rdm_policy: {range: RDMPolicy}
  dataset: {range: Dataset}
  legal_aspects: {range: LegalAspects}
  partner: {range: Partner}
  schedule: {range: Schedule}
  metadata: {range: DatasetMetadata}
  preservation: {range: Preservation}
  sensitive_data: {range: SensitiveData}
  collaboration_organisation: {range: string}

  yesno: { range: string }
  international_yesno: { range: string }

  collaboration_yesno: { range: string }
  conditions: { range: string }
  quality_assurance: { range: string }
  contact_person: { range: string }
  usage_frequency: { range: string }
  volume: { range: string }
  statutatory_approval: { range: string }
  format: { range: string }
  certification: { range: string }
  data_access_committee: { range: string }
  type: { range: string }
  access_authentication: { range: string }
  size: { range: string }
  repository_arrangements: { range: string }
  usage_description: { range: string }
  uri: { range: string }
  usage_support: { range: string }
  versioning_yesno: { range: string }
  naming_policy: { range: string }
  versioning_tool: { range: string }
  organisation_policy: { range: string }
  interoperability: { range: string }
  rdm_policy: { range: string }
  reproducibility: { range: string }
  official_approval: { range: string }
  project_start: { range: string }
  origin: { range: string }
  integration: { range: string }
  collaboration_tools: { range: string }
  creator: { range: string }
  reuse_duration: { range: string }
  system: { range: string }
  personal_data_yesno: { range: string }
  usage_infrastructure: { range: string }
  pids: { range: string }
  creation_automatic: { range: string }
  storage: { range: string }
  ethics_committee: { range: string }
  purpose: { range: string }
  sharing: { range: string }
  other: { range: string }
  project_end: { range: string }
  ipr: { range: string }