@startuml
skinparam nodesep 10
hide circle
hide empty members
class "TechnicalResources" [[{None}]] {

}
class "TechnicalResource" [[{None}]] {
    {field} description : string  
    {field} name : string  
}
class "Dataset" [[{None}]] {
    {field} data_quality_assurance : string  [0..*]
    {field} description : string  
    {field} is_reused : boolean  
    {field} issued : string  
    {field} keyword : string  [0..*]
    {field} personal_data : personal_data_options  
    {field} preservation_statement : string  
    {field} rights : string  
    {field} sensitive_data : sensitive_data_options  
    {field} title : string  
    {field} type : string  
}
"TechnicalResources" *--> "0..*" "TechnicalResource" : "items"
"Dataset" *--> "0..1" "TechnicalResources" : "technical_resource"
"Dataset" *--> "0..1" "TechnicalResources" : "technical_resource"(i)
class "TechnicalResourceID" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"TechnicalResource" *--> "0..*" "TechnicalResourceID" : "technical_resource_id"
"TechnicalResource" *--> "0..*" "TechnicalResourceID" : "technical_resource_id"(i)
class "ContributorRoles" [[{None}]] {

}
class "Contributors" [[{None}]] {

}
class "Costs" [[{None}]] {

}
class "Datasets" [[{None}]] {

}
class "Fundings" [[{None}]] {

}
class "Licenses" [[{None}]] {

}
class "PIDSystems" [[{None}]] {

}
class "SecurityAndPrivacyItems" [[{None}]] {

}
"ContributorRoles" *--> "0..*" "TechnicalResource" : "items"(i)
"Contributors" *--> "0..*" "TechnicalResource" : "items"(i)
"Costs" *--> "0..*" "TechnicalResource" : "items"(i)
"Datasets" *--> "0..*" "TechnicalResource" : "items"(i)
"Fundings" *--> "0..*" "TechnicalResource" : "items"(i)
"Licenses" *--> "0..*" "TechnicalResource" : "items"(i)
"PIDSystems" *--> "0..*" "TechnicalResource" : "items"(i)
"SecurityAndPrivacyItems" *--> "0..*" "TechnicalResource" : "items"(i)
"TechnicalResources" *--> "0..*" "TechnicalResource" : "items"(i)
class "SecurityAndPrivacyItem" [[{None}]] {
    {field} description : string  
    {field} title : string  
}
"SecurityAndPrivacyItems" *--> "0..*" "SecurityAndPrivacyItem" : "items"
"Dataset" *--> "0..1" "SecurityAndPrivacyItems" : "security_and_privacy"
"Dataset" *--> "0..1" "SecurityAndPrivacyItems" : "security_and_privacy"(i)
class "DMPData" [[{Provides high level information about the DMP, e.g. its title, modification date, etc. It is the root of this application profile. The majority of its fields are mandatory.}]] {
    {field} created : string  
    {field} description : string  
    {field} ethical_issues_description : string  
    {field} ethical_issues_report : string  
    {field} modified : string  
    {field} title : string  
}
class "RelatedIdentifier" [[{None}]] {
    {field} identifier : string  
    {field} metadata_scheme : string  
    {field} relation_type : string  
    {field} resource_type : string  
    {field} scheme_type : string  
    {field} scheme_uri : string  
    {field} type : string  
}
"DMPData" *--> "0..*" "RelatedIdentifier" : "related_identifier"
"Dataset" *--> "0..*" "RelatedIdentifier" : "related_identifier"
"Dataset" *--> "0..*" "RelatedIdentifier" : "related_identifier"(i)
"DMPData" *--> "0..*" "RelatedIdentifier" : "related_identifier"(i)
class "RDADMPCommonStandardForMachine-actionableDataManagementPlans" [[{None}]] {

}
"RDADMPCommonStandardForMachine-actionableDataManagementPlans" *--> "1" "DMPData" : "dmp"
class "Project" [[{None}]] {
    {field} description : string  
    {field} end : string  
    {field} start : string  
    {field} title : string  
}
class "ProjectID" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"Project" *--> "0..*" "ProjectID" : "project_id"
"Project" *--> "0..*" "ProjectID" : "project_id"(i)
"Project" *--> "0..1" "Fundings" : "funding"
"DMPData" *--> "0..*" "Project" : "project"
"DMPData" *--> "0..*" "Project" : "project"(i)
class "PIDSystemType" [[{None}]] {

}
class "Host" [[{To provide information on quality of service provided by infrastructure (e.g. repository) where data is stored.}]] {
    {field} availability : string  
    {field} backup_frequency : string  
    {field} backup_type : string  
    {field} description : string  
    {field} storage_type : string  
    {field} title : string  
    {field} url : string  
}
"PIDSystems" *--> "0..*" "PIDSystemType" : "items"
"Host" *--> "0..1" "PIDSystems" : "pid_system"
"Host" *--> "0..1" "PIDSystems" : "pid_system"(i)
class "Metadata" [[{None}]] {
    {field} description : string  
}
class "MetadataStandardID" [[{None}]] {
    {field} identifier : string  
    {field} type : type_options  
}
"Metadata" *--> "1..*" "MetadataStandardID" : "metadata_standard_id"
"Metadata" *--> "1..*" "MetadataStandardID" : "metadata_standard_id"(i)
class "LanguageCode" [[{Language of the metadata expressed using ISO 639-3.}]] {

}
"Metadata" *--> "1" "LanguageCode" : "language"
"Dataset" *--> "0..*" "Metadata" : "metadata"
"Dataset" *--> "0..*" "Metadata" : "metadata"(i)
class "Distribution" [[{None}]] {
    {field} access_url : string  
    {field} available_until : string  
    {field} byte_size : integer  
    {field} description : string  
    {field} download_url : string  
    {field} issued : string  
    {field} title : string  
}
class "MIMEType" [[{None}]] {

}
"Distribution" *--> "0..*" "MIMEType" : "format"
"Distribution" *--> "0..*" "MIMEType" : "format"(i)
class "License" [[{None}]] {
    {field} license_ref : string  
    {field} start_date : string  
}
"Licenses" *--> "0..*" "License" : "items"
"Distribution" *--> "0..1" "Licenses" : "license"
"Distribution" *--> "0..1" "Licenses" : "license"(i)
"DMPData" *--> "1" "LanguageCode" : "language"
"Dataset" *--> "1" "LanguageCode" : "language"
"Dataset" *--> "1" "LanguageCode" : "language"(i)
"DMPData" *--> "1" "LanguageCode" : "language"(i)
"Metadata" *--> "1" "LanguageCode" : "language"(i)
class "HostID" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"Host" *--> "0..*" "HostID" : "host_id"
"Host" *--> "0..*" "HostID" : "host_id"(i)
class "Booleanish" [[{To indicate whether there are ethical issues related to data that this DMP describes. Allowed values: yes, no, unknown}]] {

}
class "CountryCode" [[{Physical location of the data expressed using ISO 3166-1 country code.}]] {

}
class "Certification" [[{Repository certified to a recognised standard. Allowed values: din31644, dini-zertifikat, dsa, iso16363, iso16919, trac, wds, coretrustseal}]] {

}
"Host" *--> "0..1" "Booleanish" : "support_versioning"
"Host" *--> "0..1" "CountryCode" : "geo_location"
"Host" *--> "0..1" "Certification" : "certified_with"
"Distribution" *--> "0..1" "Host" : "host"
"Distribution" *--> "0..1" "Host" : "host"(i)
class "Funding" [[{None}]] {

}
class "GrantID" [[{Grant ID of the associated project}]] {
    {field} identifier : string  
    {field} type : string  
}
"Funding" *--> "0..1" "GrantID" : "grant_id"
"Funding" *--> "0..1" "GrantID" : "grant_id"(i)
"Fundings" *--> "0..*" "Funding" : "items"
"Project" *--> "0..1" "Fundings" : "funding"(i)
class "FundingStatus" [[{To express different phases of project lifecycle. Allowed values: planned, applied, granted, rejected}]] {

}
"Funding" *--> "0..1" "FundingStatus" : "funding_status"
"Funding" *--> "0..1" "FundingStatus" : "funding_status"(i)
class "FunderID" [[{Funder ID of the associated project}]] {
    {field} identifier : string  
    {field} type : string  
}
"Funding" *--> "1" "FunderID" : "funder_id"
"Funding" *--> "1" "FunderID" : "funder_id"(i)
class "DataAccess" [[{Indicates access mode for data. Allowed values: open, shared, closed}]] {

}
"Distribution" *--> "1" "DataAccess" : "data_access"
"Dataset" *--> "0..*" "Distribution" : "distribution"
"Dataset" *--> "0..*" "Distribution" : "distribution"(i)
"Datasets" *--> "0..*" "Dataset" : "items"
"DMPData" *--> "1" "Datasets" : "dataset"
"DMPData" *--> "1" "Datasets" : "dataset"(i)
class "DatasetID" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"Dataset" *--> "1" "DatasetID" : "dataset_id"
"Dataset" *--> "1" "DatasetID" : "dataset_id"(i)
class "Creator" [[{None}]] {
    {field} mbox : string  
    {field} name : string  
}
class "AlternateIdentifier" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"Dataset" *--> "0..*" "Creator" : "creator"
"Dataset" *--> "0..*" "AlternateIdentifier" : "alternate_identifier"
"Distribution" *--> "1" "DataAccess" : "data_access"(i)
class "DMPID" [[{Identifier for the DMP itself}]] {
    {field} identifier : string  
    {field} type : string  
}
"DMPData" *--> "1" "DMPID" : "dmp_id"
"DMPData" *--> "1" "DMPID" : "dmp_id"(i)
class "Contact" [[{Specifies the party which can provide any information on the DMP. This is not necessarily the DMP creator, and can be a person or an organisation.}]] {
    {field} mbox : string  
    {field} name : string  
}
"DMPData" *--> "1" "Booleanish" : "ethical_issues_exist"
"DMPData" *--> "0..1" "Costs" : "cost"
"DMPData" *--> "0..1" "Contributors" : "contributor"
"DMPData" *--> "1" "Contact" : "contact"
"DMPData" *--> "0..*" "AlternateIdentifier" : "alternate_identifier"
"RDADMPCommonStandardForMachine-actionableDataManagementPlans" *--> "1" "DMPData" : "dmp"(i)
class "Cost" [[{None}]] {
    {field} description : string  
    {field} title : string  
    {field} value : float  
}
class "CurrencyCode" [[{Allowed values defined by ISO 4217}]] {

}
"Cost" *--> "0..1" "CurrencyCode" : "currency_code"
"Cost" *--> "0..1" "CurrencyCode" : "currency_code"(i)
class "CreatorID" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"Creator" *--> "1..*" "CreatorID" : "creator_id"
"Creator" *--> "1..*" "CreatorID" : "creator_id"(i)
class "Affiliation" [[{None}]] {
    {field} name : string  
}
"Creator" *--> "0..*" "Affiliation" : "affiliation"
"Dataset" *--> "0..*" "Creator" : "creator"(i)
"Host" *--> "0..1" "CountryCode" : "geo_location"(i)
"Costs" *--> "0..*" "Cost" : "items"
"DMPData" *--> "0..1" "Costs" : "cost"(i)
class "Contributor" [[{None}]] {
    {field} mbox : string  
    {field} name : string  
}
"Contributors" *--> "0..*" "Contributor" : "items"
"DMPData" *--> "0..1" "Contributors" : "contributor"(i)
class "ContributorRole" [[{Contributors role(s) within the process of data management (incl. planning). It is recommended to use contributor types of DataCite Metadata Schema (https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/contributorType/).}]] {

}
"ContributorRoles" *--> "0..*" "ContributorRole" : "items"
"Contributor" *--> "1" "ContributorRoles" : "role"
"Contributor" *--> "1" "ContributorRoles" : "role"(i)
class "ContributorID" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"Contributor" *--> "1..*" "ContributorID" : "contributor_id"
"Contributor" *--> "1..*" "ContributorID" : "contributor_id"(i)
"Contributor" *--> "0..*" "Affiliation" : "affiliation"
class "ContactID" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"Contact" *--> "1..*" "ContactID" : "contact_id"
"Contact" *--> "1..*" "ContactID" : "contact_id"(i)
"Contact" *--> "0..*" "Affiliation" : "affiliation"
"DMPData" *--> "1" "Contact" : "contact"(i)
"Host" *--> "0..1" "Certification" : "certified_with"(i)
"DMPData" *--> "1" "Booleanish" : "ethical_issues_exist"(i)
"Host" *--> "0..1" "Booleanish" : "support_versioning"(i)
"Dataset" *--> "0..*" "AlternateIdentifier" : "alternate_identifier"(i)
"DMPData" *--> "0..*" "AlternateIdentifier" : "alternate_identifier"(i)
class "AffiliationID" [[{None}]] {
    {field} identifier : string  
    {field} type : string  
}
"Affiliation" *--> "1" "AffiliationID" : "affiliation_id"
"Affiliation" *--> "1" "AffiliationID" : "affiliation_id"(i)
"Contact" *--> "0..*" "Affiliation" : "affiliation"(i)
"Contributor" *--> "0..*" "Affiliation" : "affiliation"(i)
"Creator" *--> "0..*" "Affiliation" : "affiliation"(i)
@enduml
